[server]
browser = "default"
follow_symlink = false

[display]
default_width = "medium"
theme = "light"
cell_output = "above"
dataframes = "rich"
code_editor_font_size = 14

[ai]
rules = ""
[ai.google]

[ai.open_ai]

[ai.anthropic]

[package_management]
manager = "uv"

[language_servers.pylsp]
enable_mypy = true
enable_pylint = false
enable_pyflakes = false
enabled = true
enable_flake8 = false
enable_ruff = true
enable_pydocstyle = false

[experimental]
lsp = true
inline_ai_tooltip = true
secrets = true

[completion]
activate_on_typing = true
copilot = "codeium"

[runtime]
on_cell_change = "autorun"
auto_instantiate = true
auto_reload = "off"
reactive_tests = true
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000
output_max_bytes = 8000000

[save]
autosave = "after_delay"
format_on_save = false
autosave_delay = 1000

[formatting]
line_length = 79

[keymap]
preset = "default"
[keymap.overrides]

[snippets]
include_default_snippets = true
custom_paths = []
